---
- name: Create /etc/motd
  copy:
    dest: /etc/motd
    owner: root
    group: root
    mode: '0644'
    content: "{{ banner_msg }}"

- name: Create /etc/issue
  copy:
    dest: /etc/issue
    owner: root
    group: root
    mode: '0644'
    content: "{{ banner_msg }}"

- name: Create /etc/issue.net
  copy:
    dest: /etc/issue.net
    owner: root
    group: root
    mode: '0644'
    content: "{{ banner_msg }}"

