---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
  - name: Collect /etc/motd file system information
    stat:
      path: /etc/motd
    register: etc_motd

  - name: /etc/motd should be owned by root
    assert:
      that:
        - etc_motd.stat.uid == 0
        - etc_motd.stat.gid == 0

  - name: /etc/motd should have permissions 0644
    assert:
      that: etc_motd.stat.mode == "0644"

  - name: Collect /etc/issue file system information
    stat:
      path: /etc/issue
    register: etc_issue

  - name: /etc/issue should be owned by root
    assert:
      that:
        - etc_issue.stat.uid == 0
        - etc_issue.stat.gid == 0

  - name: /etc/issue should have permissions 0644
    assert:
      that: etc_issue.stat.mode == "0644"

  - name: Collect /etc/issue.net file system information
    stat:
      path: /etc/issue.net
    register: etc_issue_net

  - name: /etc/issue.net should be owned by root
    assert:
      that:
        - etc_issue_net.stat.uid == 0
        - etc_issue_net.stat.gid == 0

  - name: /etc/issue.net should have permissions 0644
    assert:
      that: etc_issue_net.stat.mode == "0644"

  - name: All banner files should have same contents
    assert:
      that:
        - etc_motd.stat.checksum == etc_issue.stat.checksum
        - etc_motd.stat.checksum == etc_issue_net.stat.checksum

